### PR TITLE
Filter out archived venues in GetVenuesByProviderHandler

### PR DESCRIPTION
**Pull request by timabell**
As discussed on slack, there is no use case for returning archived Venues

### CODE REVIEW

**Comment by jameslawesynergy** [comment]
> As discussed on slack, there is no use case for returning archived Venues

Have you been through the code and looked at all of the consumers of the Handler and sense-checked for returning only non-archived `Venues`?



Also, weren't there others that needed fixing up in the same way?

**Comment by timabell** [comment]
> Have you been through the code and looked at all of the consumers of the Handler and sense-checked for returning only non-archived `Venues`?

I got the impression @gunndabad already knew that it would be okay, but perhaps I should. Good call.

> Also, weren't there others that needed fixing up in the same way?

Possibly, but I'm inclined to get this out and then worry about the others if needed.

**Comment by jameslawesynergy** [comment]
I was under the impression from the slack conversation [https://dfc-beta.slack.com/archives/G01CEG7QA0H/p1610539399179200] that we weren't creating a ticket to do this work (as I had suggested, so we don't forgot to do it!), we were just going to crack on and get it done. If we maintain the current trajectory it will be forgotten and potential issues will remain within the system. I don't mind either way, but it needs to be done now or recorded so it gets done later.

**Comment by timabell** [comment]
> I was under the impression from the slack conversation [https://dfc-beta.slack.com/archives/G01CEG7QA0H/p1610539399179200] that we weren't creating a ticket to do this work (as I had suggested, so we don't forgot to do it!), we were just going to crack on and get it done. If we maintain the current trajectory it will be forgotten and potential issues will remain within the system. I don't mind either way, but it needs to be done now or recorded so it gets done later.

Is there an issue with this patch that means we shouldn't merge it or can this PR be approved?

**Comment by timabell** [comment]
I don't have the mental bandwidth for the extra analysis on top of the current task. Killing for another day.

**Comment by jameslawesynergy** [comment]
Resurrected and extended following analysis of impact to changes.

The only potential issue we might see is on FAC where an active course has an Archived Venue attached to it, in which case we'll need to fix the data and establish how that came to be.

**Pull request closed without merging**
